### ISSUE TITLE
Webpage not showing up.

### ISSUE THREAD

**Issue by shivanshsin0203** [internetarchive/bookreader#1275] opened 2023-11-09 15:17 UTC
**Description**

After executing the npm run build and installing all dependencies including webpack cli then executing npm run serve and on http://localhost:8000/BookReaderDemo/demo-simple.html nothing is showing up.

![image](https://github.com/internetarchive/bookreader/assets/139235773/39b5cb00-71b4-4a17-b9d2-7004aa403fac)

**Expectation**

The proper webpage should be showing up http://localhost:8000/BookReaderDemo/demo-simple.html

**Context**

Windows OS and Chrome browser

**Comment by lalitkumawat1m** [comment] 2023-11-16 09:13
I want to work on this issue could you please assign it to me?

**Comment by cdrini** [comment] 2023-11-16 16:58
Hi @shivanshsin0203 . Please use the Internet Archive demo for testing, the simple demo has a bug in it

**Comment by cdrini** [comment] 2023-11-16 16:59
Closing as duplicate of #1103

**Closed by cdrini** 2023-11-16 16:59 UTC

**Comment by shivanshsin0203** [comment] 2023-11-17 05:25
Hi, @cdrini.What do you mean by Internet Archive demo. I am quite a beginner so can you please guide

**Comment by cdrini** [comment] 2023-11-17 07:49
When you go to localhost 8000 ( should look like https://lucid-poitras-9a1249.netlify.app/ ), click "From internet archive"
