### ISSUE TITLE
The page index of simple demo is showing wrong page index number

### ISSUE THREAD

**Issue by raghu0812199** [internetarchive/bookreader#656] opened 2021-03-13 07:08 UTC
**Description**

> The bookreader simple demo is not showing the last page even if person has reached the final page instead it is showing index of page prior to the last page.
one can reproduce this by
1. simply run the bookreader locally and then go to http://localhost:8000/BookReaderDemo/demo-simple.html
2. Change the view to single page 

**Evidence / Screenshot (if possible)**

> 
![image](https://user-images.githubusercontent.com/72986044/111022367-59ffda80-83f8-11eb-86c7-477cbeb194fb.png)

**Expectation**

>The slider should all the way to the end and the index sec should show 5 of 5
**Context**

> operating system-Windows 10
 browser type and version- Google Chrome 

**Proposal & Constraints**

> 

**Stakeholders**

>

**Comment by Dinesh101041** [comment] 2021-03-13 13:33
I think it is duplicate of issue #648

**Closed** 2021-03-13 14:02 UTC

**Comment by raghu0812199** [comment] 2021-03-13 14:04
thank you @Dinesh101041 it was my mistake i didn't  check the other issue
