### ISSUE TITLE
DRY up Mode2Up.flipLeftToRight and Mode2Up.flipRightToLeft

### ISSUE THREAD

**Issue by cdrini** [internetarchive/bookreader#301] opened 2020-05-07 20:48 UTC
These functions have _very_ similar logic, and are largely duplicates of each other. DRY them up.

### Summary of Requirements
- [ ] Create pre-refactor unit tests for `Mode2Up.flipLeftToRight` and `Mode2Up.flipRightToLeft`
- [ ] `Mode2Up.flipLeftToRight` and `Mode2Up.flipRightToLeft` should still exist, but call a helper function which takes more parameters and reduces code duplication
- [ ] Update tests and ensure they still pass

**Comment by imskr** [comment] 2020-07-09 14:25
I can do this @cdrini I need some more details on it like how exactly you want to refactor?

**Comment by surajat17** [comment] 2020-09-25 19:27
hey @cdrini i am have forked this and running in my local device succesfully.. can you assign it to me?

**Comment by shubham00jain** [comment] 2020-09-29 12:49
@cdrini is this still open? I'd like to work on it.

**Comment by diwanshu8850** [comment] 2020-09-29 12:54
@cdrini If the issue is still not resolved would like to take it up from here on.

**Comment by ArunTeltia** [comment] 2020-10-02 21:21
@shubham00jain  @diwanshu8850  are you working on this

**Comment by ArunTeltia** [comment] 2020-10-11 15:23
Okay no reply from them so i am working on this 
@cdrini do i have to create a new file for fliping or just create the new function insite the Mode2Up.js

**Comment by ArunTeltia** [comment] 2020-10-12 17:34
Hello @cdrini  
I am approaching the refractor by this 
```
helperflipper(newIndexL, newIndexR, LeftToRight){
    this.br.refs.$brContainer.addClass("BRpageFlipping");
    const leftLeaf = this.br.twoPage.currentIndexL;
    const oldLeafEdgeWidthL = this.br.leafEdgeWidth(this.br.twoPage.currentIndexL);
    const newLeafEdgeWidthL = this.br.leafEdgeWidth(newIndexL);
    const oldLeafEdgeWidthR = this.br.twoPage.edgeWidth - oldLeafEdgeWidthL;
    const newLeafEdgeWidthR = this.br.twoPage.edgeWidth - newLeafEdgeWidthL;

    const currWidthL = this.getPageWidth(leftLeaf);
    const newWidthL = this.getPageWidth(newIndexL);
    const newWidthR = this.getPageWidth(newIndexR);
    const top = this.top();
    const scaledW = this.getPageWidth(this.br.twoPage.currentIndexR);
    const middle = this.br.twoPage.middle;
    let leafEdgeTmpW;
    let leftPixel;
    const gutter = this.br.twoPage.middle + this.gutterOffsetForIndex(newIndexL);

    if (LeftToRight) {
        leafEdgeTmpW = oldLeafEdgeWidthL - newLeafEdgeWidthL;
        leftPixel = gutter - currWidthL - leafEdgeTmpW;
    } else {
        leafEdgeTmpW = oldLeafEdgeWidthR - newLeafEdgeWidthR;
        leftPixel = gutter + scaledW;
    }
    const $twoPageViewEl = this.br.refs.$brTwoPageView;
    this.br.leafEdgeTmp = document.createElement('div');
    this.br.leafEdgeTmp.className = 'BRleafEdgeTmp';

    $(this.br.leafEdgeTmp).css({
        width: `${leafEdgeTmpW}px`,
        height: `${this.br.twoPage.height}px`,
        left: `${leftPixel}px`,
        top: `${top}px`,
        zIndex: 1000,
    }).appendTo($twoPageViewEl);

    const newWidthL = this.getPageWidth(newIndexL);
    const newWidthR = this.getPageWidth(newIndexR);

    if (LeftToRight) {
        $(this.leafEdgeL).css({
            width: `${newLeafEdgeWidthL}px`,
            left: `${gutter - currWidthL - newLeafEdgeWidthL}px`
        });

        const left = $(this.br.prefetchedImgs[leftLeaf]).offset().left;
        const right = `${$twoPageViewEl.prop('clientWidth') - left - $(this.br.prefetchedImgs[leftLeaf]).width() + $twoPageViewEl.offset().left - 2}px`;
        $(this.br.prefetchedImgs[leftLeaf]).css({
            right: right,
            left: ''
        });
    } else {
        $(this.leafEdgeR).css({
            width: `${newLeafEdgeWidthR}px`, left: `${gutter + newWidthR}px`
        });
        const speed = this.br.flipSpeed;
    }
    $(this.br.leafEdgeTmp).animate({ left: gutter }, this.br.flipSpeed, 'easeInSine');
    if (this.br.enableSearch) this.br.removeSearchHilites();

}
```
Please tell me if this is the right approach I am going to 
Or what can I do to make it look even better

**Comment by ArunTeltia** [comment] 2020-10-18 08:11
@cdrini @iisa can you please check I have refactored the code If you gave it a go I will send a pull request and start with the writing tests for this helper function 
```
helperflipper(newIndexL, newIndexR, LeftToRight){
    this.br.refs.$brContainer.addClass("BRpageFlipping");
    const leftLeaf = this.br.twoPage.currentIndexL;
    const rightLeaf = this.br.twoPage.currentIndexR;

    const oldLeafEdgeWidthL = this.br.leafEdgeWidth(leftLeaf);
    const newLeafEdgeWidthL = this.br.leafEdgeWidth(newIndexL);
    const oldLeafEdgeWidthR = this.br.twoPage.edgeWidth - oldLeafEdgeWidthL;
    const newLeafEdgeWidthR = this.br.twoPage.edgeWidth - newLeafEdgeWidthL;

    const currWidthL = this.getPageWidth(leftLeaf);
    const currWidthR = this.getPageWidth(rightLeaf);
    const newWidthL = this.getPageWidth(newIndexL);
    const newWidthR = this.getPageWidth(newIndexR);
    const top = this.top();
    const middle = this.br.twoPage.middle;
    let leafEdgeTmpWL;
    let leafEdgeTmpL;
    const speed = this.br.flipSpeed;
    const gutter = this.br.twoPage.middle + this.gutterOffsetForIndex(newIndexL);

    if (LeftToRight) {
        leafEdgeTmpWL = gutter - currWidthL - oldLeafEdgeWidthL - newLeafEdgeWidthL;
        leafEdgeTmpL = gutter + newWidthR;
    } else {
        leafEdgeTmpWL = gutter + newWidthR;
        leafEdgeTmpL = gutter - newWidthL - leafEdgeTmpW;
    }
    const $twoPageViewEl = this.br.refs.$brTwoPageView;
    this.br.leafEdgeTmp = document.createElement('div');
    this.br.leafEdgeTmp.className = 'BRleafEdgeTmp';

    $(this.br.leafEdgeTmp).css({
        width: `${leafEdgeTmpW}px`,
        height: `${this.br.twoPage.height}px`,
        left: `${leafEdgeTmpWL}px`,
        top: `${top}px`,
        zIndex: 1000,
    }).appendTo($twoPageViewEl);

    let oldFlipFromLeafIndex;
    let oldFlipToLeafIndex;
    let newFlipFromLeafIndex;
    let newFlipToLeafIndex;

    if (LeftToRight) {
        $(this.leafEdgeL).css({
            width: `${newLeafEdgeWidthL}px`,
            left: `${leafEdgeTmpWL}px`
        });

        const left = $(this.br.prefetchedImgs[leftLeaf]).offset().left;
        const right = `${$twoPageViewEl.prop('clientWidth') - left - $(this.br.prefetchedImgs[leftLeaf]).width() + $twoPageViewEl.offset().left - 2}px`;
        $(this.br.prefetchedImgs[leftLeaf]).css({
            right: right,
            left: ''
        });
        oldFlipFromLeafIndex=leftLeaf;
        oldFlipToLeafIndex=rightLeaf;
        newFlipFromLeafIndex=newIndexL;
        newFlipToLeafIndex=newIndexR;

    } else {
        $(this.leafEdgeR).css({
            width: `${newLeafEdgeWidthR}px`,
            left: `${leafEdgeTmpWL}px`
        });
        oldFlipFromLeafIndex=rightLeaf;
        oldFlipToLeafIndex=leftLeaf;
        newFlipFromLeafIndex=newIndexR;
        newFlipToLeafIndex=newIndexL;
    }

    $(this.br.leafEdgeTmp).animate({ left: gutter }, speed, 'easeInSine');
    if (this.br.enableSearch) this.br.removeSearchHilites();

    $(this.br.leafEdgeTmp).animate({ left: `${leafEdgeTmpL}px` }, speed, 'easeOutSine');
    $(this.br.prefetchedImgs[oldFlipFromLeafIndex]).animate({ width: '0px' }, speed, 'easeInSine', () => {
        this.br.$('.BRgutter').css({ left: `${gutter - this.br.twoPage.bookSpineDivWidth * 0.5}px` });
        $(this.br.prefetchedImgs[newFlipToLeafIndex]).animate({ width: `${newWidthR}px` }, speed, 'easeOutSine', () => {
            $(this.br.prefetchedImgs[newFlipFromLeafIndex]).css('zIndex', 2);
            //jquery adds display:block to the element style, which interferes with our print css
            $(this.br.prefetchedImgs[newFlipFromLeafIndex]).css('display', '');
            $(this.br.prefetchedImgs[newFlipToLeafIndex]).css('display', '');

            $(this.leafEdgeR).css({
                // Moves the right leaf edge
                width: `${this.br.twoPage.edgeWidth - newLeafEdgeWidthL}px`,
                left: `${gutter + newWidthR}px`
            });
            $(this.leafEdgeL).css({
                // Moves and resizes the left leaf edge
                width: `${newLeafEdgeWidthL}px`,
                left: `${gutter - newWidthL - newLeafEdgeWidthL}px`
            });
            // Resizes the brown border div
            $(this.br.twoPage.coverDiv).css({
                width: `${this.coverWidth(newWidthL + newWidthR)}px`,
                left: `${gutter - newWidthL - newLeafEdgeWidthL - this.br.twoPage.coverInternalPadding}px`
            });
            $(this.br.leafEdgeTmp).remove();
            this.br.leafEdgeTmp = null;
            // $$$ TODO refactor with opposite direction flip
            this.br.twoPage.currentIndexL = newFlipFromLeafIndex;
            this.br.twoPage.currentIndexR = newFlipToLeafIndex;
            this.br.twoPage.scaledWL = newWidthL;
            this.br.twoPage.scaledWR = newWidthR;
            this.br.twoPage.gutter = gutter;

            this.br.updateFirstIndex(this.br.twoPage.currentIndexL);
            this.br.displayedIndices = [newFlipFromLeafIndex, newFlipToLeafIndex];
            this.br.pruneUnusedImgs();
            this.br.prefetch();
            this.br.animating = false;

            if (this.br.enableSearch) this.br.updateSearchHilites();

            this.setMouseHandlers();

            if (this.br.animationFinishedCallback) {
                this.br.animationFinishedCallback();
                this.br.animationFinishedCallback = null;
            }
            this.br.refs.$brContainer.removeClass("BRpageFlipping");
            this.br.textSelectionPlugin?.stopPageFlip(this.br.refs.$brContainer);
            this.br.trigger('pageChanged');
        });
    });

}
```

**Comment by shreyan-invalid** [comment] 2021-02-02 19:22
Hey, I would like to work on this issue. Please assign me to it.

**Closed** 2023-04-26 23:32 UTC
Labels: difficulty: medium, refactor, good first issue
